# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import thuawood.busts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=600)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=thuawood.busts.models.upload_to_bust)),
            ],
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
