# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Namn')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='E-post')),
                ('homepage', models.URLField(blank=True, verbose_name='Hemsida')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Stad')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
